Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Helpers\\ComparisonData",
            "name": "ComparisonData",
            "summary": "Class\u0020ComparisonData",
            "url": "classes/App-Helpers-ComparisonData.html"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ComparisonData\u0020constructor.",
            "url": "classes/App-Helpers-ComparisonData.html#method___construct"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AgetNewRecord\u0028\u0029",
            "name": "getNewRecord",
            "summary": "Get\u0020the\u0020current\u0020record\u0020from\u0020the\u0020new\u0020CSV\u0020file.",
            "url": "classes/App-Helpers-ComparisonData.html#method_getNewRecord"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AsetNewRecord\u0028\u0029",
            "name": "setNewRecord",
            "summary": "Set\u0020the\u0020current\u0020record\u0020for\u0020the\u0020new\u0020CSV\u0020file.",
            "url": "classes/App-Helpers-ComparisonData.html#method_setNewRecord"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AgetOldRecord\u0028\u0029",
            "name": "getOldRecord",
            "summary": "Get\u0020the\u0020current\u0020record\u0020from\u0020the\u0020old\u0020CSV\u0020file.",
            "url": "classes/App-Helpers-ComparisonData.html#method_getOldRecord"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AsetOldRecord\u0028\u0029",
            "name": "setOldRecord",
            "summary": "Set\u0020the\u0020current\u0020record\u0020for\u0020the\u0020old\u0020CSV\u0020file.",
            "url": "classes/App-Helpers-ComparisonData.html#method_setOldRecord"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AincrementNewCounter\u0028\u0029",
            "name": "incrementNewCounter",
            "summary": "Increment\u0020the\u0020counter\u0020for\u0020new\u0020records.",
            "url": "classes/App-Helpers-ComparisonData.html#method_incrementNewCounter"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AincrementAlterCounter\u0028\u0029",
            "name": "incrementAlterCounter",
            "summary": "Increment\u0020the\u0020counter\u0020for\u0020altered\u0020records.",
            "url": "classes/App-Helpers-ComparisonData.html#method_incrementAlterCounter"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AincrementEqualCounter\u0028\u0029",
            "name": "incrementEqualCounter",
            "summary": "Increment\u0020the\u0020counter\u0020for\u0020equal\u0020records.",
            "url": "classes/App-Helpers-ComparisonData.html#method_incrementEqualCounter"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AincrementNewIndex\u0028\u0029",
            "name": "incrementNewIndex",
            "summary": "Increment\u0020the\u0020index\u0020for\u0020new\u0020records.",
            "url": "classes/App-Helpers-ComparisonData.html#method_incrementNewIndex"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AincrementOldIndex\u0028\u0029",
            "name": "incrementOldIndex",
            "summary": "Increment\u0020the\u0020index\u0020for\u0020old\u0020records.",
            "url": "classes/App-Helpers-ComparisonData.html#method_incrementOldIndex"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "Get\u0020the\u0020output\u0020data.",
            "url": "classes/App-Helpers-ComparisonData.html#method_getOutput"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AgetNewRecordIndex\u0028\u0029",
            "name": "getNewRecordIndex",
            "summary": "Get\u0020the\u0020index\u0020of\u0020the\u0020current\u0020record\u0020in\u0020the\u0020new\u0020CSV\u0020file.",
            "url": "classes/App-Helpers-ComparisonData.html#method_getNewRecordIndex"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AgetOldRecordIndex\u0028\u0029",
            "name": "getOldRecordIndex",
            "summary": "Get\u0020the\u0020index\u0020of\u0020the\u0020current\u0020record\u0020in\u0020the\u0020old\u0020CSV\u0020file.",
            "url": "classes/App-Helpers-ComparisonData.html#method_getOldRecordIndex"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AaddOutput\u0028\u0029",
            "name": "addOutput",
            "summary": "Add\u0020data\u0020to\u0020the\u0020output.",
            "url": "classes/App-Helpers-ComparisonData.html#method_addOutput"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003AmergeOutput\u0028\u0029",
            "name": "mergeOutput",
            "summary": "Merge\u0020the\u0020output\u0020data\u0020and\u0020counts\u0020for\u0020new,\u0020altered,\u0020and\u0020equal\u0020records.",
            "url": "classes/App-Helpers-ComparisonData.html#method_mergeOutput"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024newRecord",
            "name": "newRecord",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_newRecord"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024oldRecord",
            "name": "oldRecord",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_oldRecord"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024newRecordIndex",
            "name": "newRecordIndex",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_newRecordIndex"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024oldRecordIndex",
            "name": "oldRecordIndex",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_oldRecordIndex"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024newCount",
            "name": "newCount",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_newCount"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024alterCount",
            "name": "alterCount",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_alterCount"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024equalCount",
            "name": "equalCount",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_equalCount"
        },                {
            "fqsen": "\\App\\Helpers\\ComparisonData\u003A\u003A\u0024output",
            "name": "output",
            "summary": "",
            "url": "classes/App-Helpers-ComparisonData.html#property_output"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVCompareController",
            "name": "CSVCompareController",
            "summary": "",
            "url": "classes/App-Http-Controllers-CSVCompareController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVCompareController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Http-Controllers-CSVCompareController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVCompareController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020the\u0020initial\u0020index\u0020page.",
            "url": "classes/App-Http-Controllers-CSVCompareController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVCompareController\u003A\u003AuploadFiles\u0028\u0029",
            "name": "uploadFiles",
            "summary": "Handle\u0020the\u0020uploaded\u0020CSV\u0020files,\u0020compare\u0020them\u0020and\u0020show\u0020the\u0020comparison\u0020results.",
            "url": "classes/App-Http-Controllers-CSVCompareController.html#method_uploadFiles"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CSVCompareController\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/App-Http-Controllers-CSVCompareController.html#property_service"
        },                {
            "fqsen": "\\App\\Http\\Requests\\CSVUploadRequest",
            "name": "CSVUploadRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-CSVUploadRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\CSVUploadRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-CSVUploadRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\CSVUploadRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-CSVUploadRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService",
            "name": "CSVCompareService",
            "summary": "",
            "url": "classes/App-Services-CSVCompareService.html"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "Compare\u0020two\u0020CSV\u0020files\u0020and\u0020return\u0020their\u0020differences.",
            "url": "classes/App-Services-CSVCompareService.html#method_compare"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Get\u0020the\u0020CSV\u0020Reader\u0020object\u0020for\u0020a\u0020given\u0020file\u0020path.",
            "url": "classes/App-Services-CSVCompareService.html#method_getStream"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "Extract\u0020and\u0020return\u0020the\u0020headers\u0020from\u0020the\u0020CSV\u0020readers.",
            "url": "classes/App-Services-CSVCompareService.html#method_getHeaders"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AareHeadersValid\u0028\u0029",
            "name": "areHeadersValid",
            "summary": "Validate\u0020the\u0020headers\u0020of\u0020both\u0020CSV\u0020files.",
            "url": "classes/App-Services-CSVCompareService.html#method_areHeadersValid"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AfindDifferences\u0028\u0029",
            "name": "findDifferences",
            "summary": "Find\u0020and\u0020return\u0020the\u0020differences\u0020between\u0020the\u0020records\u0020of\u0020two\u0020CSV\u0020files.",
            "url": "classes/App-Services-CSVCompareService.html#method_findDifferences"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AhandleNewRecords\u0028\u0029",
            "name": "handleNewRecords",
            "summary": "Handle\u0020new\u0020records\u0020and\u0020add\u0020them\u0020to\u0020the\u0020comparison\u0020data.",
            "url": "classes/App-Services-CSVCompareService.html#method_handleNewRecords"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AhandleAlteredAndEqualRecords\u0028\u0029",
            "name": "handleAlteredAndEqualRecords",
            "summary": "Handle\u0020altered\u0020and\u0020equal\u0020records\u0020and\u0020add\u0020them\u0020to\u0020the\u0020comparison\u0020data.",
            "url": "classes/App-Services-CSVCompareService.html#method_handleAlteredAndEqualRecords"
        },                {
            "fqsen": "\\App\\Services\\CSVCompareService\u003A\u003AaddOutput\u0028\u0029",
            "name": "addOutput",
            "summary": "Add\u0020the\u0020output\u0020of\u0020the\u0020comparison\u0020to\u0020the\u0020comparison\u0020data.",
            "url": "classes/App-Services-CSVCompareService.html#method_addOutput"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/app-helpers.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Requests",
            "name": "Requests",
            "summary": "",
            "url": "namespaces/app-http-requests.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        }            ]
);
